"""Markdown reporter — generates a markdown report file."""

from __future__ import annotations

from vibe_check.engine.models import ScanReport

_GRADE_BADGES: dict[str, str] = {
    "A": "brightgreen",
    "B": "green",
    "C": "yellow",
    "D": "orange",
    "F": "red",
}


def render(report: ScanReport) -> str:
    """Generate a markdown report from a ScanReport."""
    lines: list[str] = []

    badge_color = _GRADE_BADGES.get(report.overall_grade, "lightgrey")
    badge = (
        f"![Grade](https://img.shields.io/badge/vibe--check-"
        f"{report.overall_grade}%20({report.overall_score}%25)-{badge_color})"
    )

    lines.append(f"# Vibe Check Report")
    lines.append("")
    lines.append(badge)
    lines.append("")
    lines.append(f"**Project:** `{report.project_path}`  ")
    lines.append(f"**Scanned at:** {report.scanned_at}  ")
    lines.append(f"**Files scanned:** {report.total_files}  ")

    lang_parts = [f"{lang} ({count})" for lang, count in report.files_by_language.items()]
    if lang_parts:
        lines.append(f"**Languages:** {', '.join(lang_parts)}  ")

    lines.append(f"**Overall Grade:** **{report.overall_grade}** ({report.overall_score}/100)  ")
    lines.append("")

    # Summary table
    lines.append("## Summary")
    lines.append("")
    lines.append("| Category | Info | Warn | Fail | Score | Grade |")
    lines.append("|----------|------|------|------|-------|-------|")

    for result in report.categories:
        infos = sum(1 for f in result.findings if f.severity == "info")
        warns = sum(1 for f in result.findings if f.severity == "warn")
        fails = sum(1 for f in result.findings if f.severity == "fail")
        cat_name = result.category.replace("_", " ").title()
        lines.append(
            f"| {cat_name} | {infos} | {warns} | {fails} "
            f"| {result.score} | {result.grade} |"
        )

    lines.append("")

    # Per-category details
    for result in report.categories:
        if not result.findings:
            continue

        cat_name = result.category.replace("_", " ").title()
        lines.append(f"## {cat_name}")
        lines.append("")

        for finding in result.findings:
            severity_icon = {"fail": "x", "warn": "!", "info": "i"}.get(
                finding.severity, "?"
            )
            location = ""
            if finding.file_path:
                location = f" `{finding.file_path}"
                if finding.line_number:
                    location += f":{finding.line_number}"
                location += "`"

            lines.append(
                f"- **[{severity_icon}] {finding.rule_id}:** "
                f"{finding.message}{location}"
            )
            if finding.suggestion:
                lines.append(f"  - *Suggestion:* {finding.suggestion}")
            if finding.snippet:
                lines.append(f"  - ```{finding.snippet}```")

        lines.append("")

    # Footer
    lines.append("---")
    lines.append(
        f"*Generated by [vibe-check](https://github.com/NyxToolsDev/vibe-check) "
        f"v{report.version} in {report.total_scan_time_ms:.0f}ms*"
    )
    lines.append("")

    return "\n".join(lines)
